config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do
    resources :bids, only: [:new, :create]
  end

  resources :users, except: :index 

  resources :sessions, only: [:new, :create, :destroy]

end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :product
  monetize :bid_amount_cents

  validates :bid_amount_string, presence: true
  validate :consistent

  def bid_amount_string
    bid_amount && bid_amount.format
  end

  def bid_amount_string=(val)
    if val =~ /(\d+(\.\d+)?)/
      self.bid_amount_cents = ($1.to_f * 100).to_i # convert to cents
    else
      raise "Couldn't turn this into a price: #{val.inspect}"
    end
  end

  def greater?(other)
    self.bid_amount_string > other.bid_amount_string
  end
  
private
  def consistent
    unless product.is_biddable?(self)
      errors.add(:product, "is not capable of making that bid")
    end
  end
end

app/models/concerns/amount.rb
class Amount < Struct.new(:bid_amount_string)

  include Comparable

  def <=>(other)
    self.bid_amount_string <=> other.bid_amount_string
  end

  def ==(other)
    self.bid_amount_string == other.bid_amount_string
  end


end

app/models/product.rb
require 'time_diff'

class Product < ActiveRecord::Base
  belongs_to :seller, class_name: 'User'
  has_many :bids
  monetize :starting_price_cents
  belongs_to :buyer, class_name: 'User'

  def remaining_time
    if self.end_time > Time.now.utc
      t = Time.diff(self.end_time, Time.zone.now)
      t[:diff]
    else
      "This auction has closed"
    end
  end

  def top_bid   
    bids = self.bids.sort do |bid, other_bid|
      other_bid.bid_amount_string <=> bid.bid_amount_string
    end
    bids.first
  end

  def top_bid_amount
  self.top_bid.bid_amount_string
  end

  def display_bid
    unless self.bids.none? 
      self.top_bid.bid_amount_string
    end 
  end



  def is_biddable?(requested_bid)
    in_time = self.end_time > Time.now.utc
    first_bid = self.bids.none? && (requested_bid.bid_amount_string > self.starting_price_string)
    
    if self.bids.any? 
      biddable = requested_bid.greater?(self.top_bid) 
    end
    
    in_time && (first_bid || biddable)
  end

  def strf_time
    self.end_time.strftime("%Y/%m/%d %H:%M:%S")
  end

  def starting_price_string
    starting_price && starting_price.format
  end

  def starting_price_string=(val)
    if val =~ /(\d+(\.\d+)?)/
      self.starting_price_cents = ($1.to_f * 100).to_i # convert to cents
    else
      raise "Couldn't turn this into a price: #{val.inspect}"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  has_many :products, foreign_key: :seller_id
  has_many :bids
  has_many :products, through: :bids

  validates :password, length: { minimum: 6 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if !User.find_by_id(session[:user_id])
      session[:user_id] = nil
    end
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in!"
      redirect_to new_session_path
    end
  end
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, only: [:create, :destroy]

  def new
    @bid = @product.bids.new
  end

  def create
    @bid = Bid.new bids_params
    @bid.user = current_user

    # binding.pry
    if @bid.save
      redirect_back_or_to products_path, notice: 'Bid made!'
    else
      render 'products/show'
    end
  end

  def show
    @bid = Bid.find(params[:id])
  end

private
  def bids_params
    # params.require(:bid).permit(:product_id, :bid_amount_string)
    { 
      bid_amount_string: params[:bid][:bid_amount_string],
      product_id: params[:product_id]
    }
  end

  def load_product 
    @product = Product.find(params[:product_id]) 
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  include ProductsHelper

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
    @seller = @product.seller
    @bids = @product.bids
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to products_path }
        format.js {}
      else
        format.html {render :new, alert: "Create product failed"}
        format.js {}
      end
    end
    # p.end_time = case product_params[:auction_ends_in]
    # when "1"
    #   DateTime.now + 1.week
    # when "2"
    #   Datetime.now + 1.day
    # end
    # p.save
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :seller_id, :starting_price_string, :end_time)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
   if @user = login(params[:email], params[:password])
     redirect_back_or_to(:products, notice: 'Login successful')
   else
    flash.now[:alert] = 'Login failed'
    render action: 'new'
   end
  end

  def destroy
    reset_session
    redirect_back_or_to(:products, notice: 'Logged out!')
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @products = @user.products.all
    @bids = @user.bids.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_back_or_to(products_url, :notice => "Signed up!")
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :remember)
  end

  def user
    @user ||= User.find_by(id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/products_helper.rb
module ProductsHelper

  # def present_bid?(product)
  #   if product.top_bid.present?
  #     if current_user && current_user.bids.present?
  #       if current_user.bids.any? do |bid|
  #         bid.user_id == product.top_bid.user_id
  #       end
        
  #       "#{product.top_bid_amount} This is your bid!"
  #       else
  #         "#{product.top_bid_amount}"
  #       end
  #     end
  #   else
  #     "Starting Price: #{product.starting_price}"
  #   end
  # end

  def bid_wrapper(product)
    if product.bids.any?
      if product.top_bid.user == current_user
        "Your bid: #{product.top_bid_amount}"
      else
        "#{product.top_bid_amount}"
      end
    else
      "Starting Price: #{product.starting_price}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bids/_form.html.erb
<%= form_for([@product, @bid]) do |f| %>

    <div class="field">
      <%= f.label :bid_amount_string %><br>
      <%= f.text_field :bid_amount_string %>
    </div>

    <div class="actions" style="margin-top: 10px;">
      <%= f.submit %>
    </div>

<% end %>

app/views/bids/create.html.erb
<h1>Bids#create</h1>
<p>Find me in app/views/bids/create.html.erb</p>

app/views/bids/new.html.erb
<h1>Bids#new</h1>
<p>Find me in app/views/bids/new.html.erb</p>

app/views/bids/show.html.erb
<h1>Bids#show</h1>
<p>Find me in app/views/bids/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auctioneer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>

  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  <header>

    <p class='user_info'>
      <% if current_user %>
        Signed in as <%= link_to current_user.email, user_path(current_user.id) %>. <br>
        <%= link_to "Log Out", session_path('current'), :method => :delete %>
      <% else %>
        <%= link_to "Log In", new_session_path %> or
        <%= link_to "Sign Up", new_user_path %>
      <% end %>

    <h1>Auctioneer</h1>

    </p>
  </header>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for (@product) do |f|  %>
  
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="field">
    <%=  f.label :starting_price_string %>
    <%= f.number_field :starting_price_string, placeholder: 'Amount in USD' %>
  </div>

  <div class="field">
    <%= f.label :end_time %>
    <%= f.datetime_select :end_time, discard_year: :true, hour_step: 1, ampm: true %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/_product.html.erb
<script src="/assets/jquery.countdown.js"></script>

<p><strong><%= link_to product.name, product %></strong></p>
  
  <p><strong>Description: </strong><%= product.description %></p>
  
  <p><strong><%= bid_wrapper(product) %></strong></p>
  
  <p><strong>Remaining Time: </strong>
    <div id='countdown_<%= product.id %>'><%= product.remaining_time %>
      <span id="clock_<%= product.id %>'"></span>
    </div>
  </p>

  <p></p>

  <% if product.end_time > DateTime.now.utc%>
    <script>
      $('#countdown_<%= product.id %>').countdown('<%= product.strf_time %>', function(event) { 
        $(this).text(
          event.strftime('%-D days %-H h %M min %S sec')
        );
      });
    </script>
  <% end %>
<br>

app/views/products/create.html.erb
<h1>Products#create</h1>
<p>Find me in app/views/products/create.html.erb</p>

app/views/products/destroy.html.erb
<h1>Products#destroy</h1>
<p>Find me in app/views/products/destroy.html.erb</p>

app/views/products/edit.html.erb
<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>

app/views/products/index.html.erb
<%=  link_to "Add a product", new_product_path, class: "add-product"%>

<h3>All Products</h3>

<div id="products">
  <%= render @products %>
</div>

app/views/products/new.html.erb
<h1>Enter in a New Product</h1>

<%= render 'form' %>

<br>

<%= link_to 'Back To Products', products_path %>

app/views/products/product.js.erb
// var remaining_time = function(product){
//   var now = moment();
//   var time = <%= product.end_time %> - now
// }

app/views/products/show.html.erb
<h4><%= link_to "Back To Products", products_path %></h4>

<%= render partial: "product", locals: { product: @product } %>


<h2>Bids</h2> 

<h3>Top bid: <%= @product.display_bid %>
</h3> 

<% if current_user %>
  <h3>Make a bid</h3>

  <%= form_for([@product, Bid.new]) do |f| %>

    <div class="field">
      <%= f.label :bid_amount_string %><br>
      <%= f.text_field :bid_amount_string %>
    </div>

    <div class="actions" style="margin-top: 10px;">
      <%= f.submit %>
    </div>

  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to make a bid.</p>

<% end %>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign-up</h1>

<%= form_for @user do |f|%>

  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="action">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<p>
<% @bids.each do |bid| %>
  <%= render 'products/product', :product => bid.product %> 
<% end %>
</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>